package action

const (
	ERR_NO_PUBLIC_ENDPOINT_SATISFIED_BY_PAYLOAD = "ERR_NO_PUBLIC_ENDPOINT_SATISFIED_BY_PAYLOAD"
	ERR_NO_HANDLER                              = "ERR_NO_HANDLER"
	ENV_JWT_SECRET                              = "JWT_SECRET"

	ERR_UNPARSABLE_JWT                      = "ERR_UNPARSABLE_JWT"
	ERR_INVALID_CLAIMS                      = "ERR_INVALID_CLAIMS"
	ERR_MISSING_PARAMETERS_DESCRIPTION      = "ERR_MISSING_PARAMETERS_DESCRIPTION"
	ERR_PARSE_PAYLOAD_NOT_IMPLEMENTED_YET   = "ERR_PARSE_PAYLOAD_NOT_IMPLEMENTED_YET"
	ERR_PARAMETER_NOT_REQUIRED_NOR_OPTIONAL = "ERR_PARAMETER_NOT_REQUIRED_NOR_OPTIONAL"

	FATAL_NO_ACTION_DESCRIPTION = "NO_ACTION_DESCRIPTION"
)

var jwt_secret []byte
