package resource

const (
	ERR_WRONG_PAYLOAD                        = "ERR_WRONG_PAYLOAD"
	ERR_NO_GET_ACTION_FOUND                  = "ERR_NO_GET_ACTION_FOUND"
	ERR_MULTIPLE_GETS_CAN_SATISFY_THIS_QUERY = "ERR_MULTIPLE_GETS_CAN_SATISFY_THIS_QUERY"

	FATAL_NO_RESOURCE_DESCRIPTION   = "NO_RESOURCE_DESCRIPTION"
	FATAL_NO_RESOURCE_ENDPOINT      = "NO_RESOURCE_ENDPOINT"
	FATAL_GET_ACTION_ALREADY_EXISTS = "FATAL_GET_ACTION_ALREADY_EXISTS"

	DEFAULT_ACTION = "__DEFAULT_ACTION__"

	GET_STRICTLY_BETTER = 1
	GET_STRICTLY_WORSE  = -1
	GET_EQUAL           = 0
)
