package resource

const (
	FATAL_NO_RESOURCE_DESCRIPTION   = "NO_RESOURCE_DESCRIPTION"
	FATAL_NO_RESOURCE_ENDPOINT      = "NO_RESOURCE_ENDPOINT"
	FATAL_GET_ACTION_ALREADY_EXISTS = "FATAL_GET_ACTION_ALREADY_EXISTS"

	DEFAULT_ACTION = "__DEFAULT_ACTION__"

	GET_NAME = "_n"
)
